Fixing up deploy to not be interactive

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -3,17 +3,17 @@
 #########################################################################################
 #components default version
 #########################################################################################
-GRAFANA_DEFAULT_VERSION=6.0.2
-PROMETHEUS_DEFAULT_VERSION=v2.8.1
-PROMETHEUS_OPERATOR_DEFAULT_VERSION=v0.29.0
-PROMETHEUS_STORAGE_DEFAULT_RETENTION=168h
+GRAFANA_DEFAULT_VERSION=6.2.5
+PROMETHEUS_DEFAULT_VERSION=v2.11.1
+PROMETHEUS_OPERATOR_DEFAULT_VERSION=v0.31.1
+PROMETHEUS_STORAGE_DEFAULT_RETENTION=336h
 PROMETHEUS_STORAGE_DEFAULT_VOLUME_SIZE=40Gi
 PROMETHEUS_DEFAULT_MEMORY_REQUEST=1Gi
-ALERTMANAGER_DEFAULT_VERSION=v0.16.1
-NODE_EXPORTER_DEFAULT_VERSION=v0.17.0
-KUBE_STATE_METRICS_DEFAULT_VERSION=v1.5.0
-NODE_LABEL_DEFAULT_KEY=beta.kubernetes.io/monit
-NODE_LABEL_DEFAULT_VALUE=prometheus
+ALERTMANAGER_DEFAULT_VERSION=v0.18.0
+NODE_EXPORTER_DEFAULT_VERSION=v0.18.1
+KUBE_STATE_METRICS_DEFAULT_VERSION=v1.6.0
+NODE_LABEL_DEFAULT_KEY=nodegroup-type
+NODE_LABEL_DEFAULT_VALUE=backend-workloads-aw
 DEFAULT_NAMESPACE=monitoring
 
 #########################################################################################
@@ -53,13 +53,19 @@ fi
 
 echo -e "${ORANGE}Creating a new branch for this work"
 
-git checkout -b $(date +"%Y%m%d-%H%M%S")
+GITOUT=$(git checkout -b $(date +"%Y%m%d-%H%M%S") 2>&1)
+
+if [ "$?" != "0" ]; them
+  echo -e "${RED}${GITOUT}"
+  echo -e "${RED}FATAL error checking out branch, exiting"
+  exit 1
+fi
 
 
 #Namespace
-read -p "Enter desired namespace to deploy prometheus [$DEFAULT_NAMESPACE]: " NAMESPACE
+#read -p "Enter desired namespace to deploy prometheus [$DEFAULT_NAMESPACE]: " NAMESPACE
 NAMESPACE=${NAMESPACE:-$DEFAULT_NAMESPACE}
-tput sgr0
+#tput sgr0
 
 echo -e "${BLUE}Creating ${ORANGE}${NAMESPACE} ${BLUE}namespace."
 kubectl create namespace "$NAMESPACE"
@@ -140,67 +146,67 @@ done
 #set components version
 ###########################################################################################
 echo -e "${ORANGE}Setting components version"
-tput sgr0
+#tput sgr0
 
 #Prometheus Operator
-read -p "Enter Prometheus Operator version [$PROMETHEUS_OPERATOR_DEFAULT_VERSION]: " PROMETHEUS_OPERATOR_VERSION
+#read -p "Enter Prometheus Operator version [$PROMETHEUS_OPERATOR_DEFAULT_VERSION]: " PROMETHEUS_OPERATOR_VERSION
 PROMETHEUS_OPERATOR_VERSION=${PROMETHEUS_OPERATOR_VERSION:-$PROMETHEUS_OPERATOR_DEFAULT_VERSION}
 
 #Prometheus
-echo
-read -p "Enter Prometheus version [$PROMETHEUS_DEFAULT_VERSION]: " PROMETHEUS_VERSION
+#echo
+#read -p "Enter Prometheus version [$PROMETHEUS_DEFAULT_VERSION]: " PROMETHEUS_VERSION
 PROMETHEUS_VERSION=${PROMETHEUS_VERSION:-$PROMETHEUS_DEFAULT_VERSION}
 
 #Prometheus Storage Retention
-echo
-read -p "Enter Prometheus storage retention period in hours [$PROMETHEUS_STORAGE_DEFAULT_RETENTION]: " PROMETHEUS_STORAGE_RETENTION
+#echo
+#read -p "Enter Prometheus storage retention period in hours [$PROMETHEUS_STORAGE_DEFAULT_RETENTION]: " PROMETHEUS_STORAGE_RETENTION
 PROMETHEUS_STORAGE_RETENTION=${PROMETHEUS_STORAGE_RETENTION:-$PROMETHEUS_STORAGE_DEFAULT_RETENTION}
 
 #Prometheus Storage Volume Size
-echo
-read -p "Enter Prometheus storage volume size [$PROMETHEUS_STORAGE_DEFAULT_VOLUME_SIZE]: " PROMETHEUS_STORAGE_VOLUME_SIZE
+#echo
+#read -p "Enter Prometheus storage volume size [$PROMETHEUS_STORAGE_DEFAULT_VOLUME_SIZE]: " PROMETHEUS_STORAGE_VOLUME_SIZE
 PROMETHEUS_STORAGE_VOLUME_SIZE=${PROMETHEUS_STORAGE_VOLUME_SIZE:-$PROMETHEUS_STORAGE_DEFAULT_VOLUME_SIZE}
 
 #Prometheus Memory Request
-echo
-read -p "Enter Prometheus memory request in Gi or Mi [$PROMETHEUS_DEFAULT_MEMORY_REQUEST]: " PROMETHEUS_MEMORY_REQUEST
+#echo
+#read -p "Enter Prometheus memory request in Gi or Mi [$PROMETHEUS_DEFAULT_MEMORY_REQUEST]: " PROMETHEUS_MEMORY_REQUEST
 PROMETHEUS_MEMORY_REQUEST=${PROMETHEUS_MEMORY_REQUEST:-$PROMETHEUS_DEFAULT_MEMORY_REQUEST}
 
 #Grafana
-echo
-read -p "Enter Grafana version [$GRAFANA_DEFAULT_VERSION]: " GRAFANA_VERSION
+#echo
+#read -p "Enter Grafana version [$GRAFANA_DEFAULT_VERSION]: " GRAFANA_VERSION
 GRAFANA_VERSION=${GRAFANA_VERSION:-$GRAFANA_DEFAULT_VERSION}
 
 #Alertmanager
-echo
-read -p "Enter Alert Manager version [$ALERTMANAGER_DEFAULT_VERSION]: " ALERTMANAGER_VERSION
+#echo
+#read -p "Enter Alert Manager version [$ALERTMANAGER_DEFAULT_VERSION]: " ALERTMANAGER_VERSION
 ALERTMANAGER_VERSION=${ALERTMANAGER_VERSION:-$ALERTMANAGER_DEFAULT_VERSION}
 
 #Node Exporter
-echo
-read -p "Enter Node Exporter version [$NODE_EXPORTER_DEFAULT_VERSION]: " NODE_EXPORTER_VERSION
+#echo
+#read -p "Enter Node Exporter version [$NODE_EXPORTER_DEFAULT_VERSION]: " NODE_EXPORTER_VERSION
 NODE_EXPORTER_VERSION=${NODE_EXPORTER_VERSION:-$NODE_EXPORTER_DEFAULT_VERSION}
 
 #Kube State Metrics
-echo
-read -p "Enter Kube State Metrics version [$KUBE_STATE_METRICS_DEFAULT_VERSION]: " KUBE_STATE_METRICS_VERSION
+#echo
+#read -p "Enter Kube State Metrics version [$KUBE_STATE_METRICS_DEFAULT_VERSION]: " KUBE_STATE_METRICS_VERSION
 KUBE_STATE_METRICS_VERSION=${KUBE_STATE_METRICS_VERSION:-$KUBE_STATE_METRICS_DEFAULT_VERSION}
 
 #Prometheus External URL
-echo
-read -p "Enter Prometheus external Url [$PROMETHEUS_DEFAULT_EXTERNAL_URL]: " PROMETHEUS_EXTERNAL_URL
+#echo
+#read -p "Enter Prometheus external Url [$PROMETHEUS_DEFAULT_EXTERNAL_URL]: " PROMETHEUS_EXTERNAL_URL
 PROMETHEUS_EXTERNAL_URL=${PROMETHEUS_EXTERNAL_URL:-$PROMETHEUS_DEFAULT_EXTERNAL_URL}
 
 #Alertmanager External URL
-echo
-read -p "Enter Alertmanager external Url [$ALERTMANAGER_DEFAULT_EXTERNAL_URL]: " ALERTMANAGER_EXTERNAL_URL
+#echo
+#read -p "Enter Alertmanager external Url [$ALERTMANAGER_DEFAULT_EXTERNAL_URL]: " ALERTMANAGER_EXTERNAL_URL
 ALERTMANAGER_EXTERNAL_URL=${ALERTMANAGER_EXTERNAL_URL:-$ALERTMANAGER_DEFAULT_EXTERNAL_URL}
 
 #Dedicated nodes?
-echo
-echo -e "${ORANGE}Do you want to use ${WHITE}NodeSelector ${ORANGE} to assign monitoring components on dedicated nodes?"
-tput sgr0
-read -p "Y/N [N]: " use_dedicated_nodes
+#echo
+#echo -e "${ORANGE}Do you want to use ${WHITE}NodeSelector ${ORANGE} to assign monitoring components on dedicated nodes?"
+#tput sgr0
+#read -p "Y/N [N]: " use_dedicated_nodes
 
 #if so, fill out this form...
 if [[ $use_dedicated_nodes =~ ^([yY][eE][sS]|[yY])$ ]]; then
@@ -209,10 +215,10 @@ if [[ $use_dedicated_nodes =~ ^([yY][eE][sS]|[yY])$ ]]; then
   echo -e "${RED}Make sure you label the nodes correctly. The default label is: ${WHITE}beta.kubernetes.io/monit=prometheus"
   tput sgr0
 
-  read -p "Node label key [$NODE_LABEL_DEFAULT_KEY]: " NODE_LABEL_KEY
+ # read -p "Node label key [$NODE_LABEL_DEFAULT_KEY]: " NODE_LABEL_KEY
   NODE_LABEL_KEY=${NODE_LABEL_KEY:-$NODE_LABEL_DEFAULT_KEY}
 
-  read -p "Node label value [$NODE_LABEL_DEFAULT_VALUE]: " NODE_LABEL_VALUE
+ # read -p "Node label value [$NODE_LABEL_DEFAULT_VALUE]: " NODE_LABEL_VALUE
   NODE_LABEL_VALUE=${NODE_LABEL_VALUE:-$NODE_LABEL_DEFAULT_VALUE}
 
   sed -i -e 's,node_label_key,'"$NODE_LABEL_KEY"',g' manifests/alertmanager/alertmanager.yaml
@@ -276,10 +282,10 @@ sed -i -e 's,ALERTMANAGER_EXTERNAL_URL,'"$ALERTMANAGER_EXTERNAL_URL"',g' manifes
 #configure alert channels
 ##########################################################################################################################################
 #SMTP
-echo
+#echo
 echo -e "${BLUE}Do you want to set up an SMTP relay?"
-tput sgr0
-read -p "Y/N [N]: " use_smtp
+#tput sgr0
+#read -p "Y/N [N]: " use_smtp
 
 #if so, fill out this form...
 if [[ $use_smtp =~ ^([yY][eE][sS]|[yY])$ ]]; then
@@ -312,10 +318,10 @@ if [[ $use_smtp =~ ^([yY][eE][sS]|[yY])$ ]]; then
 fi
 
 #Do you want to set up slack?
-echo
-echo -e "${BLUE}Do you want to set up slack alerts?"
-tput sgr0
-read -p "Y/N [N]: " use_slack
+#echo
+#echo -e "${BLUE}Do you want to set up slack alerts?"
+#tput sgr0
+#read -p "Y/N [N]: " use_slack
 
 #if so, fill out this form...
 if [[ $use_slack =~ ^([yY][eE][sS]|[yY])$ ]]; then
@@ -378,6 +384,7 @@ echo
 echo -e "${ORANGE}Deploying Grafana"
 tput sgr0
 
+kctl apply -f manifests/grafana/dashboards
 kctl apply -f manifests/grafana
 
 echo
